### ISSUE TITLE
Shrink amount of Messages Per Second

### ISSUE THREAD

**Issue by le5h** [DevHeap/collatz_conjecture#11]
Client (aka web browser) acts like "Denial-of-Service" when it gets all results on the fly.
It is better to send messages in chunks (array of result for example).
I think it is okay to send 2-5 messages per second (lower bound is 1, higher is around 30).

**Comment by Aljutor** [comment]
Implemented simple solution with minimal time limit between messages to client 148637f999f5e649f2e69c1ea0e0a2787d0dbbf0
