### ISSUE TITLE
Basic Frontend

### ISSUE THREAD

**Issue by Aljutor** [DevHeap/collatz_conjecture#5]
We need Basic version of frontend interface that fullfill requirements.

UI:
* UI should have a field to type in an integer and button calculate. After clicking the calculate the button should say stop, which kills the connection.
* UI should work both on desktop and on mobile.
* From each value we should show; n (seed integer), path length, highest number, average number in path and calculation time.
* Results should be listed in table like fashion on desktop and as list of data blocks in mobile
* Results should be added to the list one-by-one as soon as an answer is ready (reinfo!("starting worker {}", n);info!("starting worker {}", n);member to keep meaningful order)
* When item is added to the list it should be obvious to user which one got added (recomending to use css animations)
* (Optional) Generate a SVG based histogram diagram that shows the frequency of path lengths (use SVG manipulation to update it on fly)

**Comment by Aljutor** [comment]
@gingerDevilish Pls review all text for front page

**Comment by ghost** [comment]
@Aljutor Ok, doing, please review my readme already)

**Comment by ghost** [comment]
@Aljutor done, check out another PR
